### ISSUE TITLE
Basic introduction of various functions of Pandas library

### ISSUE THREAD

**Issue by palprashant2002** [maheshjainckd/Hacktoberfest2022-for-everyone#1068]
Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real-world data analysis in Python.

**Comment by palprashant2002** [comment]
Please add this issue to repo, add label hacktoberfest and assign it to me...

**Comment by KhushiiAgarwal** [comment]
Please assign this to me
