### ISSUE TITLE
Deleting whole Linked List in CPP

### ISSUE THREAD

**Issue by Vanshika-Batra** [maheshjainckd/Hacktoberfest2022-for-everyone#1159]
Hey @maheshjainckd! I'd like to contribute by adding the code of deleting the whole linked list in CPP under the label of Hacktoberfest2022. Kindly assign it to me.

**Comment by Abhishek-Nag29** [comment]
hey @maheshjainckd  I would like to contribute on this work  by adding the code part of deleting the whole linked list in cpp under Hactoberfest2022 label .please assign it to me.

**Comment by ijaz-ali-dev** [comment]
Hey @maheshjainckd! I'd like to contribute by adding the code under the label Hacktoberfest2022. Kindly assign it to me.

**Comment by Chetnagupta27** [comment]
hey @maheshjainckd I would like to contribute on this work by adding the code part of deleting the whole linked list in cpp under Hactoberfest2022 label .please assign it to me.
