### ISSUE TITLE
I wish to add a program to find Permutation and Combination in CPP folder

### ISSUE THREAD

**Issue by aditya-464** [maheshjainckd/Hacktoberfest2022-for-everyone#140]
I wish to add a program to find Permutation and Combination in CPP folder.

**Please assign this issue to me under the "hacktoberfest" label**

**Comment by aditya-464** [comment]
Thank you @maheshjainckd

**Comment by durgeshsingh02** [comment]
can you assign me this issue

**Comment by malikzi21** [comment]
I am adding pull request kindly merge it

**Comment by Anukool1729** [comment]
if this issue is still not resolved could you please assign it to me.
