### ISSUE TITLE
Recursion folder in Java

### ISSUE THREAD

**Issue by Rajpreetkaur02** [maheshjainckd/Hacktoberfest2022-for-everyone#141]
I would like to add a recursion folder under Java programs in which I will add popular problems like N-Queens, Knight's tour, etc.

please assign it to me.

**Comment by maheshjainckd** [comment]
Assigned.

**Comment by Rajpreetkaur02** [comment]
I have created a pull request for the same, kindly see to it.
#147

**Comment by Rajpreetkaur02** [comment]
I have created another pull request #464 Please check.

Thank you for your patience.

**Comment by Anushree1291** [comment]
I would like to add a recrsion folder that has dynamic programing, backtracking, Conquer and divide and other advanced recursion problems. Please do assign me the task.

**Comment by shrutimeg** [comment]
I want to work add a recursion folder  kindly assign this to me
