### ISSUE TITLE
Add testimonial 

### ISSUE THREAD

**Issue by khushimarothi** [maheshjainckd/Hacktoberfest2022-for-everyone#142]
I want to add testimonial section code.
Tech stack used:- Html, CSS and JS.

Please assign it to me for hacktoberfest 2022.

**Comment by maheshjainckd** [comment]
Assigned.

**Comment by khushimarothi** [comment]
This project shows excluded on my hacktoberfest profile @maheshjainckd

**Comment by Anushree1291** [comment]
@maheshjainckd I have also added the Pull request. Please do review it. This is my first time participating in hacktober fest. If there is an error from my side, do tell me.

**Comment by khushimarothi** [comment]
> @maheshjainckd I have also added the Pull request. Please do review it. This is my first time participating in hacktober fest. If there is an error from my side, do tell me.

This issue is already resolved.  You need to create some other issue.

**Comment by maheshjainckd** [comment]
> This project shows excluded on my hacktoberfest profile @maheshjainckd

Yes, It got excluded from hacktoberfest2022.

**Comment by khushimarothi** [comment]
> > This project shows excluded on my hacktoberfest profile @maheshjainckd
> 
> Yes, It got excluded from hacktoberfest2022.

Why :( . This means the contributions will not be counted

**Comment by maheshjainckd** [comment]
> > > This project shows excluded on my hacktoberfest profile @maheshjainckd
> > 
> > 
> > Yes, It got excluded from hacktoberfest2022.
> 
> Why :( . This means the contributions will not be counted

you can contribute to below project.
https://github.com/dikshantrajput/Hacktoberfest-accepted-2022
