### ISSUE TITLE
Mean and Median of an Array

### ISSUE THREAD

**Issue by Sowham-3098** [maheshjainckd/Hacktoberfest2022-for-everyone#149]
I want to add this code to this repository.
Please assign me and add the Hacktoberfest tag

**Comment by Sowham-3098** [comment]
@maheshjainckd Please assign me

**Comment by beastvarun** [comment]
@maheshjainckd I'm a new programmer ,I have good grasp on C and CPP language. Currently i am learning DSA, so i want to  add code to this repository.
please assign me this for hactoberfest2022.

**Comment by Dwaipayan-Maz** [comment]
Please assign me.

**Comment by arshya-garg** [comment]
I would like to contribute to this issue, so please assign it to me.

**Comment by Saurabhk1975** [comment]
i want to do assign me @maheshjainckd
