### ISSUE TITLE
Want to add a program to find 1's Complement and 2's Complement of a number in CPP

### ISSUE THREAD

**Issue by Sowham-3098** [maheshjainckd/Hacktoberfest2022-for-everyone#150]
@maheshjainckd Please assign me this task and tag the Hacktoberfest 2022

**Comment by akshitsangwan** [comment]
Hey @Sowham-3098, I am interested to contribute to this task. Can you please assign me this task?

**Comment by Sowham-3098** [comment]
@maheshjainckd Please assign me this task.
