### ISSUE TITLE
Factorial of a number in cpp

### ISSUE THREAD

**Issue by mrsparkle-70** [maheshjainckd/Hacktoberfest2022-for-everyone#210]
A solution for this will be added by me

**Comment by ishita1505** [comment]
Please assign this issue to me

**Comment by chiragchandnani10** [comment]
Please assign this issue to me under "Hacktoberfest" title
I am a new programmer and I would like to contribute to this.
Thanks!

**Comment by Garvit414** [comment]
I want to contribute to this under "Hacktoberfest 2022" title.
Please assign this issue to me.

**Comment by vishwasgowdahv** [comment]
Assign to me I’ll do it
