### ISSUE TITLE
Infix to Postfix using Stack

### ISSUE THREAD

**Issue by SiddhantPawar03** [maheshjainckd/Hacktoberfest2022-for-everyone#278]
I'm a participant of hacktoberfest-2022.
I would perform infix to postfix operation to enhance stack usage. Would like to contribute to this repository.
Please accept my issue

**Comment by himanshu17-2000** [comment]
Hello there, @maheshjainckd ,  I would like to contribute to this issue, therefore kindly give it to me.

**Comment by SiddhantPawar03** [comment]
> I'm a participant of hacktoberfest-2022. I would perform infix to postfix operation to enhance stack usage. Would like to contribute to this repository. Please accept my issue

/assign

**Comment by arshya-garg** [comment]
I would like to contribute to this issue, so please assign it to me
