### ISSUE TITLE
Basic form website using php sql to store the data

### ISSUE THREAD

**Issue by chetansingh-2** [maheshjainckd/Hacktoberfest2022-for-everyone#320]
Please assign this task to me. I want to add my project under web development folder. @maheshjainckd

**Comment by maheshjainckd** [comment]
@chetansingh-2 you can also contribute to these repos, make sure you don't spam :)
https://github.com/dikshantrajput/hacktoberfest-2022-react
https://github.com/dikshantrajput/Hacktoberfest-accepted-2022
