### ISSUE TITLE
I want to add Black-Jack Game

### ISSUE THREAD

**Issue by Harshul02** [maheshjainckd/Hacktoberfest2022-for-everyone#338]
It is a web based Game project created using HTML, CSS and JavaScript.

Please assign it to me for hacktoberfest 2022.

**Comment by RhyshaKachari** [comment]
@maheshjainckd I'd like to take up this issue. I can solve this issue using Python.Kindly assign this issue to me.

**Comment by maheshjainckd** [comment]
@Harshul02 you can also contribute to these repos, make sure you don't spam :)
https://github.com/dikshantrajput/hacktoberfest-2022-react
https://github.com/dikshantrajput/Hacktoberfest-accepted-2022
