### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by Harshul02** [maheshjainckd/Hacktoberfest2022-for-everyone#342]
I have created a Chrome Extension which is used to save important links or tabs.

Please assign it to me for hacktoberfest 2022.

![Screenshot (180)](https://user-images.githubusercontent.com/95930860/193398274-69688fb7-b5fc-45a2-87c6-76f372fd60d4.jpg)

**Comment by sumitbaroniya** [comment]
chrome extension added
