### ISSUE TITLE
Kadane's Algorithm in cpp

### ISSUE THREAD

**Issue by stutimohta20** [maheshjainckd/Hacktoberfest2022-for-everyone#345]
Please assign this issue to me @maheshjainckd under hacktoberfest

**Comment by RavishGupta** [comment]
#include <bits/stdc++.h>
using namespace std;
 
int maxSubArraySum(int a[], int size)
{
    int max_so_far = INT_MIN, max_ending_here = 0;
 
    for (int i = 0; i < size; i++) {
        max_ending_here = max_ending_here + a[i];
        if (max_so_far < max_ending_here)
            max_so_far = max_ending_here;
 
        if (max_ending_here < 0)
            max_ending_here = 0;
    }
    return max_so_far;
}
 
// Driver Code
int main()
{
    int a[] = { -2, -3, 4, -1, -2, 1, 5, -3 };
    int n = sizeof(a) / sizeof(a[0]);
 
    // Function Call
    int max_sum = maxSubArraySum(a, n);
    cout << "Maximum contiguous sum is " << max_sum;
    return 0;
}

**Comment by sagnik2001** [comment]
I have already created a pr for this issue

**Comment by maheshjainckd** [comment]
Closing this issue because code for kadane algorithm is already present in repository. Kindly check repository before opening any new issues. Thanks

**Comment by RavishGupta** [comment]
please check my pr median of two sorted arrays
