### ISSUE TITLE
I would like to implement Binary Trees in C++

### ISSUE THREAD

**Issue by chiragchandnani10** [maheshjainckd/Hacktoberfest2022-for-everyone#413]
I would like to implement Binary Trees in C++ for this project. 
Please assign this to be a HacktoberFest. Thanks!

**Comment by AyushBorage28** [comment]
I am an experienced dsa programmer with 4star rating on codechef pls assign this issue to me

**Comment by AyushBorage28** [comment]
under the hacktoberfest label

**Comment by anush8858** [comment]
I am 5star with 30,000 rank on hackerrank . Please assign this to me.
