### ISSUE TITLE
Maximum Difference Between Two Elements in array

### ISSUE THREAD

**Issue by ritishbhardwaj** [maheshjainckd/Hacktoberfest2022-for-everyone#439]
This algorithm will help to find out the maximum difference between two elements in array such that index of larger element is greater than index of smaller element.

**Comment by ritishbhardwaj** [comment]
@maheshjainckd 
Please assign me this issue

**Comment by Jyotisaini-2001** [comment]
Hii, I am interested in contributing the code of Maximum Difference Between Two Elements in array. Please assign me this issue.
