### ISSUE TITLE
Face Recognition Using Python

### ISSUE THREAD

**Issue by shivamsdk** [maheshjainckd/Hacktoberfest2022-for-everyone#469]
For Hacktoberfest 2022

**Comment by dheerajgajula02** [comment]
is this official for hacktober fest 2022?
I would like to work on this? @shivamsdk

**Comment by maheshjainckd** [comment]
@shivamsdk @dheerajgajula02 you can also contribute to these repos for hacktoberfest2022 make sure you don't spam :)
https://github.com/dikshantrajput/hacktoberfest-2022-react
https://github.com/dikshantrajput/Hacktoberfest-accepted-2022

**Comment by Mani628** [comment]
Hi @maheshjainckd . I am a newbie to this open source contest. I am looking forward to learn many new things. I am ready with the code. Can you plz assign me this under label"hacktoberfest22" .
