### ISSUE TITLE
Color ball dancing on the screen game

### ISSUE THREAD

**Issue by stubborn-1508** [maheshjainckd/Hacktoberfest2022-for-everyone#487]
I would like to add javascript code of adding infinite balls on the screen by clicking on the screen and dragging the arrow to adjust the speed and throw it out on the screen.[https://color-balls.vercel.app/](url)

**Comment by RhyshaKachari** [comment]
Hiii @maheshjainckd I'd like to take up this issue :) This can be done with simple CSS animation. Kindly assign this to me.

**Comment by maheshjainckd** [comment]
@RhyshaKachari @stubborn-1508

**Comment by stubborn-1508** [comment]
Please can you assign this issue under the label hacktoberfest.
