### ISSUE TITLE
Find first and last occurrence of any number in an array

### ISSUE THREAD

**Issue by Shreya241** [maheshjainckd/Hacktoberfest2022-for-everyone#521]
I want to write a code that will give the index of the first and last occurrence of a number in a given array. @maheshjainckd please assign this to me under hacktoberfest2022

**Comment by maheshjainckd** [comment]
@Shreya241 you can also contribute to these repos, make sure you don't spam :)
https://github.com/dikshantrajput/hacktoberfest-2022-react
https://github.com/dikshantrajput/Hacktoberfest-accepted-2022

**Comment by AyushBorage28** [comment]
I am an experienced dsa programmer. Please assign this task to me.

**Comment by maheshjainckd** [comment]
> @Shreya241 you can also contribute to these repos, make sure you don't spam :) https://github.com/dikshantrajput/hacktoberfest-2022-react https://github.com/dikshantrajput/Hacktoberfest-accepted-2022

@AyushBorage28

**Comment by Shreya241** [comment]
> @Shreya241 you can also contribute to these repos, make sure you don't spam :) https://github.com/dikshantrajput/hacktoberfest-2022-react https://github.com/dikshantrajput/Hacktoberfest-accepted-2022

Sure, Thanks :)

**Comment by Shreya241** [comment]
@maheshjainckd this repos are excluded form hacktoberfest2022.

**Comment by maheshjainckd** [comment]
Yes, Not sure why it's happening.

**Comment by sumitbaroniya** [comment]
@maheshjainckd please assign me this issue  under hacktoberfest2022.

**Comment by Sundesh7** [comment]
@maheshjainckd Can you please assign me this issue under hacktoberfest2022 ?

**Comment by 123shanawaz** [comment]
hey! I want to write a code that will give the index of the first and last occurrence of a number in a given array. @maheshjainckd please assign this to me under hacktoberfest2022

**Comment by Vivek-raj-64** [comment]
Please assign this to me.

**Comment by xx-abhijeet-xx** [comment]
hello sir ! can you assign this issue to me? I will solve this issue in any programming language.

**Comment by Akash-moon** [comment]
Hello @maheshjainckd  sir, I want to contribute my efforts on this problem.
plz assign it to me under hacktoberfest22.

**Comment by itzzsoumya** [comment]
Hey, I want to contribute on this issue. Please assign this task to me.

**Comment by shrutimeg** [comment]
I want to solve this issue under hacktoberfest22 please assign this issue.

**Comment by RP2025** [comment]
Please assign me this issue, I would love to contribute in it using python

**Comment by saurav1207** [comment]
Hello @maheshjainckd sir,
I would like to contribute my code in C++ for this issue under Hacktoberfest2022.
Could you please assign me with this issue?
Thank you!!

**Comment by aditya10003** [comment]
NOT-PARTICIPATING
is coming on hactoberfest
please approve it
