### ISSUE TITLE
Subset Generation using Bit Masking in C++

### ISSUE THREAD

**Issue by Anjani27** [maheshjainckd/Hacktoberfest2022-for-everyone#533]
Hi, @maheshjainckd I would like to contribute to this repo and add a program of Subset Generation using Bit Masking in C++ .
Please assign this to me under Hacktoberfest .
Thanks!!

**Comment by maheshjainckd** [comment]
@Anjani27 you can also contribute to this repo https://github.com/dikshantrajput/Hacktoberfest-accepted-2022

**Comment by HARSHSUHANE17** [comment]
created this . Please check and merge my PR #675

**Comment by himanshucse-19** [comment]
I want to contribute to this repository!!

**Comment by Akash-moon** [comment]
Hello @maheshjainckd  sir, I want to contribute my efforts on this problem.
plz assign it to me under hacktoberfest22.

**Comment by RP2025** [comment]
@maheshjainckd I would like to contribute in this issue, kindly assign me this
