### ISSUE TITLE
Add 2 question of Array in cpp

### ISSUE THREAD

**Issue by sanyayaa** [maheshjainckd/Hacktoberfest2022-for-everyone#590]
Hi, @maheshjainckd  I would like to contribute to this repository

I want to add 2 Questions in Array Practice folder
1. Merge Two sorted Array 
2. Rotate an Array

Please assign this to me under Hacktoberfest .
Thanks!!

**Comment by nimeshika06** [comment]
Hi, @maheshjainckd I would like to contribute to this repository

I want to add 2 Questions to Array Practice folder
             1.Merge Overlapping subintervals
              2. repeat and missing numbers
Please assign this to me under Hacktoberfest.
Thanks!!
