### ISSUE TITLE
Simon Game usisng Javascript

### ISSUE THREAD

**Issue by sumitkr2000** [maheshjainckd/Hacktoberfest2022-for-everyone#628]
Hey @maheshjainckd I have made an awesome game using javascript. I want to add this project in this repo. Can you please assign me this issue. Thank you. Below is the screenshot of the game.

![Screenshot (314)](https://user-images.githubusercontent.com/100675296/193463600-ea21c87e-8559-446a-8a6a-5aca6180d6b3.png)

**Comment by Amitpawar88** [comment]
Hello @maheshjainckd  I want to add this project, I already made this game using Javascript, can you please assign me the issue.
This is my first PR. 
Here is link :   [Simon Game](https://amitpawar88.github.io/Simon/)

**Comment by MahenoorAhsan** [comment]
hey! @maheshjainckd please assign me this project .
I have already made it ,only few changes of images are required.
looking forward for your reply.

**Comment by Shubhamsingh2747** [comment]
Hey @maheshjainckd , I recently completed making the classic Simon game using Javascript and would like to contribute. Please assign me this issue. Here is a screenshot:

![Screenshot 2022-10-05 220021](https://user-images.githubusercontent.com/72337858/194113243-3779b47f-e741-444f-bc7f-6e1fb2416d09.jpg)

**Comment by sumitkr2000** [comment]
@maheshjainckd I asked it first. I should get it.
