### ISSUE TITLE
Height of Binary Tree 

### ISSUE THREAD

**Issue by Dharansh-Neema** [maheshjainckd/Hacktoberfest2022-for-everyone#645]
Recursively calculating height of left and right subtrees

**Comment by Dharansh-Neema** [comment]
@maheshjainckd Can you please assign this issue to me

**Comment by PandaSupremacy** [comment]
I would like to work on this issue.

**Comment by PandaSupremacy** [comment]
The height of a subtree is 1+ max(height of left subtree, height of right subtree) . It can be calculated recursively.

**Comment by nisthajnn** [comment]
please assign this to me

**Comment by Shubhamsingh2747** [comment]
Hey @maheshjainckd , please assign me this issue. I would really like to contribute.
