### ISSUE TITLE
Create a beautiful music player web app

### ISSUE THREAD

**Issue by codingkush** [maheshjainckd/Hacktoberfest2022-for-everyone#649]
This music player contain play, pause and next and previous song features and you can listen beautiful songs

**Comment by codingkush** [comment]
Pls assign to me this issue under hacktobetfest'22

**Comment by sumitbaroniya** [comment]
Please assign to me this issue under hacktobetfest'22

**Comment by codingkush** [comment]
I also want to work on it bro ....you can work on digitial clock app
