### ISSUE TITLE
Vigenere Cipher encryption and decryption-Python

### ISSUE THREAD

**Issue by deveshparmar** [maheshjainckd/Hacktoberfest2022-for-everyone#694]
hey, @maheshjainckd  i want to contribute this issue under Hacktoberfest please assign it to me.

**Comment by jawadkhanpk** [comment]
Hey I have developed my own Algorithm using Ceaser Cifer Technique in Python I wanted to contribute this to issue #649.
Please assign me this issue. Thanks
