### ISSUE TITLE
Valid parentheses

### ISSUE THREAD

**Issue by UMESH-042** [maheshjainckd/Hacktoberfest2022-for-everyone#713]
I want to add a code for Valid parentheses to check if the given string is in Balanced parentheses or not.

**Comment by reshukr97** [comment]
can you please assign me this?

**Comment by nisthajnn** [comment]
please assign this to me @UMESH-042

**Comment by Mani628** [comment]
Hi @UMESH-042 . I am a newbie to this open source contest. I am looking forward to learn many new things. I am ready with the code. Can you plz assign me this under label"hacktoberfest22" .

**Comment by reshukr97** [comment]
Hi @UMESH-042 can you please assign tis to me under #815

**Comment by 1Alisha** [comment]
Please assign this work to me

**Comment by Jyotisaini-2001** [comment]
Hii, I am interested in contributing the code of Valid parentheses. Please assign me this issue.

**Comment by ritika21-code** [comment]
I want to contribute to this issue. please assign this issue to me.
