### ISSUE TITLE
Weather App made with JS

### ISSUE THREAD

**Issue by Korak-Sengupta** [maheshjainckd/Hacktoberfest2022-for-everyone#812]

**Comment by Korak-Sengupta** [comment]
Let me submit a JS mini project of Weather App

**Comment by Shubhamsingh2747** [comment]
Hey @maheshjainckd , I already have this project with dynamic background and would like to contribute. Please assign me this issue. Here are few screenshots:

![ss2](https://user-images.githubusercontent.com/72337858/194114775-4c05bec7-b6a3-49ff-b02e-2c048af61527.jpg)


![ss1](https://user-images.githubusercontent.com/72337858/194114841-44b4c606-2b1b-43bc-b02c-1d437d6540f2.jpg)

**Comment by Korak-Sengupta** [comment]
Arey bhai..🤣 competition kyu badha raha hai..aur kaha jaa na...pehle maine
PR maara hai

**Comment by Korak-Sengupta** [comment]
Bro, i too have dynamic background, and have made the PR before you, as well as the Issue.
