### ISSUE TITLE
Temperature converter 

### ISSUE THREAD

**Issue by aparnamittal** [maheshjainckd/Hacktoberfest2022-for-everyone#832]
Add a temperature converter made using HTML, CSS, Javascript. It can convert temperature from celcius to farenheit and vice versa

**Comment by 22tanyabansal** [comment]
Hey @maheshjainckd I want to contribute on this issue. Please assign this task to me under hacktoberfest.

**Comment by aparnamittal** [comment]
@22tanyabansal  I have already made the PR for this issue.

**Comment by roytanmay** [comment]
@maheshjainckd , please assign me this task.
I want to contribute over this.
