### ISSUE TITLE
Clock using Javascript

### ISSUE THREAD

**Issue by Vivek-raj-64** [maheshjainckd/Hacktoberfest2022-for-everyone#857]
I want to add a clock made using javascript in the folder. Please assign this task to me @maheshjainckd .

**Comment by skinnyiam** [comment]
I can contribute on this issue , can you please assign it to me

**Comment by roytanmay** [comment]
I would like to contribute over this. 
Please assign me this task!

**Comment by 002ayush** [comment]
I request you to please assign this to me.
I want to contribute on this issue.

**Comment by 9520prashant** [comment]
Hello, I want to contribute in this , please assign me this issue!

**Comment by ritika21-code** [comment]
I want to contribute to this issue. please assign this issue to me.
