### ISSUE TITLE
Adding stack using queue Implementation

### ISSUE THREAD

**Issue by manshi23** [maheshjainckd/Hacktoberfest2022-for-everyone#923]
I want to implement stack using queue in the stack question , kindly assign this topic to  me under hactoberfest.

**Comment by rohitpadage** [comment]
I would like to implement the stack using queue in python. Please assign the issue asap.

**Comment by Jyotisaini-2001** [comment]
Hii, I am interested in contributing the code of Palindrome Linked List problem. Please assign me this issue.
