### ISSUE TITLE
Adding Css to the calculator

### ISSUE THREAD

**Issue by manshi23** [maheshjainckd/Hacktoberfest2022-for-everyone#924]
Hey , I want to add css in the calculator . I 'll make the interface as like glass of multicolour.
pls assign this to me under hacktoberfest 2022

**Comment by itzzsoumya** [comment]
Hey, I want to contribute on this issue. Please assign this task to me.

**Comment by el3v3n011** [comment]
hello! i want to contibute to this project. pls assign it to me

**Comment by coderboy-yash** [comment]
Hey, I am interested to contribute on this issue. Can you assign this task to me.

**Comment by ritika21-code** [comment]
I want to contribute to this issue. please assign this issue to me.

**Comment by anjaliisonii** [comment]
Please assign this work to me. I will contribute code to this issue ..Kindy assign me this work.
