### ISSUE TITLE
sorting programs in java

### ISSUE THREAD

**Issue by Ishnoor-kaur** [maheshjainckd/Hacktoberfest2022-for-everyone#938]
hey i can contribute bubble sort and selection sort programs in java. please assign this to me

**Comment by Samir433** [comment]
@maheshjainckd Hey I can contribute all 5 sorting algorithm in java  and also in python . please assign this to me

**Comment by jawadkhanpk** [comment]
Hi, I can contribute to this issue I have a strong profile in DSA, Please assign me this issue so that I can start contribution to it

**Comment by Yadnyesh-Dashpute** [comment]
Hello @maheshjainckd I would like to Contribute. I know the popular sorting Algorithms like merge sort, quick sort, bubble sort etc. Please assign me this issue

**Comment by shrutimeg** [comment]
hello kindly assign this to me I want to solve this issue

**Comment by Dipanjan2910** [comment]
Kindly assign this to me

**Comment by prabhleenn** [comment]
please assign me this
