### ISSUE TITLE
ping pong game using python

### ISSUE THREAD

**Issue by mayank-del** [maheshjainckd/Hacktoberfest2022-for-everyone#954]
@maheshjainckd  Can I add my Ping pong game project in python Under hacktoberfest 22

**Comment by mayank-del** [comment]
@maheshjainckd  please assign this issue to me

**Comment by jawadkhanpk** [comment]
Hey I'm experienced python developer please assign this issue to me so that I can contribute Ping Pong game to this repo. Thanks
