### ISSUE TITLE
Palindrome Linked List

### ISSUE THREAD

**Issue by harshita9621** [maheshjainckd/Hacktoberfest2022-for-everyone#959]
Please assign this issue to me @maheshjainckd  under hacktoberfest.

**Comment by divyanshagarwal053** [comment]
Please assign this issue to me

**Comment by Jyotisaini-2001** [comment]
Hii, I am interested in contributing the code of Palindrome Linked List problem in cpp. Please assign me this issue.

**Comment by Sakshi2002-Sinha** [comment]
Hello, Please assign me this issue.
Thanks in advance :)

**Comment by 9520prashant** [comment]
Hy , I am DSA mentor , I want to contribute in this issue , please assign this issue !

**Comment by ritika21-code** [comment]
I want to contribute to this issue. please assign this issue to me.
