### ISSUE TITLE
Add a full stack project 

### ISSUE THREAD

**Issue by ayushsaha1018** [maheshjainckd/Hacktoberfest2022-for-everyone#998]
I want to add a full stack project made using MERN stack. You can see it [here ](https://jobify-cyberninja.herokuapp.com/landing).
Github [repo](https://github.com/ayushsaha1018/jobify)

**Comment by SJ-Kumar** [comment]
I would like to add my project here. Please assign.

**Comment by Souviksamanta34** [comment]
Hey, I want to contribute in this issue.
